nopCommerce-release-4.80.5/src/Plugins/Nop.Plugin.Tax.Avalara/Models/ItemClassification/AddProductToClassificationListModel.cs
using Nop.Web.Areas.Admin.Models.Catalog;
using Nop.Web.Framework.Models;

namespace Nop.Plugin.Tax.Avalara.Models.ItemClassification;

/// <summary>
/// Represents a product list model to add for classification
/// </summary>
public record AddProductToClassificationListModel : BasePagedListModel<ProductModel>
{
}

nopCommerce-release-4.80.5/src/Plugins/Nop.Plugin.Tax.Avalara/Models/ItemClassification/AddProductToClassificationModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Plugin.Tax.Avalara.Models.ItemClassification;

/// <summary>
/// Represents a product model to add for classification
/// </summary>
public record AddProductToClassificationModel : BaseNopModel
{
    #region Ctor

    public AddProductToClassificationModel()
    {
        SelectedProductIds = new List<int>();
    }

    #endregion

    #region Properties

    public IList<int> SelectedProductIds { get; set; }

    #endregion
}

nopCommerce-release-4.80.5/src/Plugins/Nop.Plugin.Tax.Avalara/Models/ItemClassification/AddProductToClassificationSearchModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Nop.Web.Framework.Models;
using Nop.Web.Framework.Mvc.ModelBinding;

namespace Nop.Plugin.Tax.Avalara.Models.ItemClassification;

/// <summary>
/// Represents a product search model to add for classification
/// </summary>
public record AddProductToClassificationSearchModel : BaseSearchModel
{
    #region Ctor

    public AddProductToClassificationSearchModel()
    {
        AvailableCategories = new List<SelectListItem>();
        AvailableManufacturers = new List<SelectListItem>();
        AvailableStores = new List<SelectListItem>();
        AvailableVendors = new List<SelectListItem>();
        AvailableProductTypes = new List<SelectListItem>();
    }

    #endregion

    #region Properties

    [NopResourceDisplayName("Admin.Catalog.Products.List.SearchProductName")]
    public string SearchProductName { get; set; }

    [NopResourceDisplayName("Admin.Catalog.Products.List.SearchCategory")]
    public int SearchCategoryId { get; set; }

    [NopResourceDisplayName("Admin.Catalog.Products.List.SearchManufacturer")]
    public int SearchManufacturerId { get; set; }

    [NopResourceDisplayName("Admin.Catalog.Products.List.SearchStore")]
    public int SearchStoreId { get; set; }

    [NopResourceDisplayName("Admin.Catalog.Products.List.SearchVendor")]
    public int SearchVendorId { get; set; }

    [NopResourceDisplayName("Admin.Catalog.Products.List.SearchProductType")]
    public int SearchProductTypeId { get; set; }

    public IList<SelectListItem> AvailableCategories { get; set; }

    public IList<SelectListItem> AvailableManufacturers { get; set; }

    public IList<SelectListItem> AvailableStores { get; set; }

    public IList<SelectListItem> AvailableVendors { get; set; }

    public IList<SelectListItem> AvailableProductTypes { get; set; }

    #endregion
}

nopCommerce-release-4.80.5/src/Plugins/Nop.Plugin.Tax.Avalara/Models/ItemClassification/ItemClassificationListModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Plugin.Tax.Avalara.Models.ItemClassification;

/// <summary>
/// Represents a item classification list model
/// </summary>
public record ItemClassificationListModel : BasePagedListModel<ItemClassificationModel>
{
}

nopCommerce-release-4.80.5/src/Plugins/Nop.Plugin.Tax.Avalara/Models/ItemClassification/ItemClassificationModel.cs
using Nop.Web.Framework.Models;
using Nop.Web.Framework.Mvc.ModelBinding;

namespace Nop.Plugin.Tax.Avalara.Models.ItemClassification;

/// <summary>
/// Represents a item classification model
/// </summary>
public record ItemClassificationModel : BaseNopEntityModel
{
    #region Properties

    [NopResourceDisplayName("Plugins.Tax.Avalara.ItemClassification.Product")]
    public int ProductId { get; set; }
    [NopResourceDisplayName("Plugins.Tax.Avalara.ItemClassification.Product")]
    public string ProductName { get; set; }

    [NopResourceDisplayName("Plugins.Tax.Avalara.ItemClassification.HSClassificationRequestId")]
    public string HSClassificationRequestId { get; set; }

    [NopResourceDisplayName("Plugins.Tax.Avalara.ItemClassification.Country")]
    public int CountryId { get; set; }
    [NopResourceDisplayName("Plugins.Tax.Avalara.ItemClassification.Country")]
    public string CountryName { get; set; }

    [NopResourceDisplayName("Plugins.Tax.Avalara.ItemClassification.HSCode")]
    public string HSCode { get; set; }

    [NopResourceDisplayName("Plugins.Tax.Avalara.ItemClassification.UpdatedDate")]
    public DateTime UpdatedDate { get; set; }

    #endregion
}

nopCommerce-release-4.80.5/src/Plugins/Nop.Plugin.Tax.Avalara/Models/ItemClassification/ItemClassificationSearchModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Nop.Web.Framework.Models;
using Nop.Web.Framework.Mvc.ModelBinding;

namespace Nop.Plugin.Tax.Avalara.Models.ItemClassification;

/// <summary>
/// Represents a item classification search model
/// </summary>
public record ItemClassificationSearchModel : BaseSearchModel
{
    #region Ctor

    public ItemClassificationSearchModel()
    {
        AvailableCountries = new List<SelectListItem>();
    }

    #endregion

    #region Properties

    [NopResourceDisplayName("Plugins.Tax.Avalara.ItemClassification.Search.Country")]
    public int SearchCountryId { get; set; }

    public IList<SelectListItem> AvailableCountries { get; set; }

    #endregion
}

nopCommerce-release-4.80.5/src/Plugins/Nop.Plugin.Tax.Avalara/Controllers/ItemClassificationController.cs
using Microsoft.AspNetCore.Mvc;
using Nop.Core.Domain.Catalog;
using Nop.Plugin.Tax.Avalara.Models.ItemClassification;
using Nop.Plugin.Tax.Avalara.Services;
using Nop.Services.Catalog;
using Nop.Services.Directory;
using Nop.Services.Helpers;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Services.Tax;
using Nop.Web.Areas.Admin.Controllers;
using Nop.Web.Areas.Admin.Factories;
using Nop.Web.Areas.Admin.Models.Catalog;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Models.Extensions;
using Nop.Web.Framework.Mvc;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Plugin.Tax.Avalara.Controllers;

public class ItemClassificationController : BaseAdminController
{
    #region Fields

    protected readonly AvalaraTaxManager _avalaraTaxManager;
    protected readonly IBaseAdminModelFactory _baseAdminModelFactory;
    protected readonly ICountryService _countryService;
    protected readonly IDateTimeHelper _dateTimeHelper;
    protected readonly ILocalizationService _localizationService;
    protected readonly INotificationService _notificationService;
    protected readonly IPermissionService _permissionService;
    protected readonly IProductService _productService;
    protected readonly ITaxPluginManager _taxPluginManager;
    protected readonly ItemClassificationService _itemClassificationService;

    #endregion

    #region Ctor

    public ItemClassificationController(AvalaraTaxManager avalaraTaxManager,
        IBaseAdminModelFactory baseAdminModelFactory,
        ICountryService countryService,
        IDateTimeHelper dateTimeHelper,
        ILocalizationService localizationService,
        INotificationService notificationService,
        IPermissionService permissionService,
        IProductService productService,
        ITaxPluginManager taxPluginManager,
        ItemClassificationService itemClassificationService)
    {
        _avalaraTaxManager = avalaraTaxManager;
        _baseAdminModelFactory = baseAdminModelFactory;
        _countryService = countryService;
        _dateTimeHelper = dateTimeHelper;
        _localizationService = localizationService;
        _notificationService = notificationService;
        _permissionService = permissionService;
        _productService = productService;
        _taxPluginManager = taxPluginManager;
        _itemClassificationService = itemClassificationService;
    }

    #endregion

    #region Methods

    [HttpPost]
    [CheckPermission(StandardPermission.Configuration.MANAGE_TAX_SETTINGS)]
    public async Task<IActionResult> List(ItemClassificationSearchModel searchModel)
    {
        //get item classification
        var itemClassification = await _itemClassificationService.GetItemClassificationAsync(
            pageIndex: searchModel.Page - 1,
            pageSize: searchModel.PageSize,
            countryId: searchModel.SearchCountryId,
            productId: null);

        //prepare grid model
        var model = await new ItemClassificationListModel().PrepareToGridAsync(searchModel, itemClassification, () =>
        {
            return itemClassification.SelectAwait(async item => new ItemClassificationModel
            {
                Id = item.Id,
                ProductId = item.ProductId,
                ProductName = (await _productService.GetProductByIdAsync(item.ProductId))?.Name ?? "",
                HSClassificationRequestId = item.HSClassificationRequestId,
                CountryId = item.CountryId,
                CountryName = (await _countryService.GetCountryByIdAsync(item.CountryId))?.Name ?? "*",
                HSCode = item.HSCode,
                UpdatedDate = await _dateTimeHelper.ConvertToUserTimeAsync(item.UpdatedOnUtc, DateTimeKind.Utc)
            });
        });

        return Json(model);
    }

    [HttpPost]
    [CheckPermission(StandardPermission.Configuration.MANAGE_TAX_SETTINGS)]
    public async Task<IActionResult> Update(ItemClassificationModel model)
    {
        var item = await _itemClassificationService.GetItemClassificationByIdAsync(model.Id)
            ?? throw new ArgumentException("No record found");

        item.HSCode = model.HSCode;

        await _itemClassificationService.UpdateItemClassificationAsync(item);

        return new NullJsonResult();
    }

    [HttpPost]
    [CheckPermission(StandardPermission.Configuration.MANAGE_TAX_SETTINGS)]
    public async Task<IActionResult> DeleteSelected(List<int> selectedIds)
    {
        if (!selectedIds?.Any() ?? true)
            return NoContent();

        var recordsToDelete = new List<int>();

        foreach (var id in selectedIds)
        {
            var item = await _itemClassificationService.GetItemClassificationByIdAsync(id);
            if (item is null)
                continue;

            recordsToDelete.Add(item.Id);
        }
        await _itemClassificationService.DeleteItemsAsync(recordsToDelete);

        return new NullJsonResult();
    }

    [CheckPermission(StandardPermission.Configuration.MANAGE_TAX_SETTINGS)]
    public async Task<IActionResult> ClearAll()
    {
        await _itemClassificationService.ClearItemClassificationAsync();

        return Json(new { Result = true });
    }

    [CheckPermission(StandardPermission.Catalog.PRODUCTS_VIEW)]
    [CheckPermission(StandardPermission.Configuration.MANAGE_TAX_SETTINGS)]
    public async Task<IActionResult> ProductToClassification()
    {
        var model = new AddProductToClassificationSearchModel();
        await _baseAdminModelFactory.PrepareProductTypesAsync(model.AvailableProductTypes);
        await _baseAdminModelFactory.PrepareCategoriesAsync(model.AvailableCategories);
        await _baseAdminModelFactory.PrepareManufacturersAsync(model.AvailableManufacturers);
        await _baseAdminModelFactory.PrepareStoresAsync(model.AvailableStores);
        await _baseAdminModelFactory.PrepareVendorsAsync(model.AvailableVendors);
        model.SetPopupGridPageSize();

        return View("~/Plugins/Tax.Avalara/Views/ItemClassification/ProductToClassification.cshtml", model);
    }

    [HttpPost]
    [CheckPermission(StandardPermission.Catalog.PRODUCTS_VIEW)]
    [CheckPermission(StandardPermission.Configuration.MANAGE_TAX_SETTINGS)]
    public async Task<IActionResult> ProductListToClassification(AddProductToClassificationSearchModel searchModel)
    {
        var products = await _productService.SearchProductsAsync(showHidden: true,
            keywords: searchModel.SearchProductName,
            productType: searchModel.SearchProductTypeId > 0 ? (ProductType?)searchModel.SearchProductTypeId : null,
            categoryIds: new List<int> { searchModel.SearchCategoryId },
            manufacturerIds: new List<int> { searchModel.SearchManufacturerId },
            storeId: searchModel.SearchStoreId,
            vendorId: searchModel.SearchVendorId,
            pageIndex: searchModel.Page - 1, pageSize: searchModel.PageSize);

        var model = new AddProductToClassificationListModel().PrepareToGrid(searchModel, products, () =>
        {
            return products.Select(product => new ProductModel
            {
                Id = product.Id,
                Name = product.Name,
                Sku = product.Sku,
                Price = product.Price,
                Published = product.Published
            }).ToList();
        });

        return Json(model);
    }

    [HttpPost]
    [FormValueRequired("save")]
    [CheckPermission(StandardPermission.Catalog.PRODUCTS_VIEW)]
    [CheckPermission(StandardPermission.Configuration.MANAGE_TAX_SETTINGS)]
    public async Task<IActionResult> ProductToClassification(AddProductToClassificationModel model)
    {
        await _itemClassificationService.AddItemClassificationAsync(model.SelectedProductIds?.ToList());

        ViewBag.RefreshPage = true;

        return View("~/Plugins/Tax.Avalara/Views/ItemClassification/ProductToClassification.cshtml", new AddProductToClassificationSearchModel());
    }

    [CheckPermission(StandardPermission.Configuration.MANAGE_TAX_SETTINGS)]
    public async Task<IActionResult> StartClassification()
    {
        var items = (await _itemClassificationService.GetItemClassificationAsync())
            .Where(x => string.IsNullOrEmpty(x.HSClassificationRequestId))
            .ToList();
        foreach (var item in items)
        {
            var (classification, error) = await _avalaraTaxManager.ClassificationProductsAsync(item);

            if (!string.IsNullOrEmpty(error))
                return Json(new { success = false, message = error });

            if (!string.IsNullOrEmpty(classification?.Id))
            {
                //save classification id for future use (get hsCode)
                item.HSClassificationRequestId = classification.Id;
                item.UpdatedOnUtc = DateTime.UtcNow;
                await _itemClassificationService.UpdateItemClassificationAsync(item);
            }
        }

        return Json(new { success = true, message = await _localizationService.GetResourceAsync("Plugins.Tax.Avalara.ItemClassification.Sync.Success") });
    }

    #endregion
}

nopCommerce-release-4.80.5/src/Plugins/Nop.Plugin.Tax.Avalara/Views/ItemClassification/ProductToClassification.cshtml
@model AddProductToClassificationSearchModel

@{
    Layout = "_AdminPopupLayout";

    //page title
    ViewBag.PageTitle = T("Plugins.Tax.Avalara.ItemClassification.AddProduct").Text;
}

@if (ViewBag.RefreshPage == true)
{
    <script>
        try { window.opener.document.forms['@(Context.Request.Query["formId"])'].@(Context.Request.Query["btnId"]).click(); }
        catch (e) { }
        window.close();
    </script>
}
else
{
    <form asp-controller="ItemClassification" asp-action="ProductToClassification"
          asp-route-btnId="@Context.Request.Query["btnId"]"
          asp-route-formId="@Context.Request.Query["formId"]">
        <div class="content-header clearfix">
            <h1 class="float-left">
                @T("Plugins.Tax.Avalara.ItemClassification.AddProduct")
            </h1>
            <div class="float-right">
                &nbsp;
            </div>
        </div>

        <section class="content">
            <div class="container-fluid">
                <div class="form-horizontal">
                    <div class="cards-group">
                        <div class="card card-default card-search card-popup">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="form-group row">
                                            <div class="col-sm-5">
                                                <nop-label asp-for="SearchProductName" />
                                            </div>
                                            <div class="col-sm-7">
                                                <nop-editor asp-for="SearchProductName" />
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <div class="col-sm-5">
                                                <nop-label asp-for="SearchProductTypeId" />
                                            </div>
                                            <div class="col-sm-7">
                                                <nop-select asp-for="SearchProductTypeId" asp-items="Model.AvailableProductTypes" />
                                            </div>
                                        </div>
                                        <div class="form-group row" @(Model.AvailableCategories.SelectionIsNotPossible() ? Html.Raw("style=\"display:none\"") : null)>
                                            <div class="col-sm-5">
                                                <nop-label asp-for="SearchCategoryId" />
                                            </div>
                                            <div class="col-sm-7">
                                                <nop-select asp-for="SearchCategoryId" asp-items="Model.AvailableCategories" />
                                            </div>
                                        </div>
                                        <div class="form-group row" @(Model.AvailableVendors.SelectionIsNotPossible() ? Html.Raw("style=\"display:none\"") : null)>
                                            <div class="col-sm-5">
                                                <nop-label asp-for="SearchVendorId" />
                                            </div>
                                            <div class="col-sm-7">
                                                <nop-select asp-for="SearchVendorId" asp-items="Model.AvailableVendors" />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group row" @(Model.AvailableStores.SelectionIsNotPossible() ? Html.Raw("style=\"display:none\"") : null)>
                                            <div class="col-sm-5">
                                                <nop-label asp-for="SearchStoreId" />
                                            </div>
                                            <div class="col-sm-7">
                                                <nop-select asp-for="SearchStoreId" asp-items="Model.AvailableStores" />
                                            </div>
                                        </div>
                                        <div class="form-group row" @(Model.AvailableManufacturers.SelectionIsNotPossible() ? Html.Raw("style=\"display:none\"") : null)>
                                            <div class="col-sm-5">
                                                <nop-label asp-for="SearchManufacturerId" />
                                            </div>
                                            <div class="col-sm-7">
                                                <nop-select asp-for="SearchManufacturerId" asp-items="Model.AvailableManufacturers" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12">
                                        <button type="button" id="search-products" class="btn btn-primary btn-search">
                                            <i class="fas fa-magnifying-glass"></i>
                                            @T("Admin.Common.Search")
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="card card-default">
                            <div class="card-body">
                                @await Html.PartialAsync("Table", new DataTablesModel
                                {
                                    Name = "products-grid",
                                    UrlRead = new DataUrl("ProductListToClassification", "ItemClassification", null),
                                    SearchButtonId = "search-products",
                                    Length = Model.PageSize,
                                    LengthMenu = Model.AvailablePageSizes,
                                    Filters = new List<FilterParameter>
                                    {
                                        new FilterParameter(nameof(Model.SearchProductName)),
                                        new FilterParameter(nameof(Model.SearchProductTypeId)),
                                        new FilterParameter(nameof(Model.SearchCategoryId)),
                                        new FilterParameter(nameof(Model.SearchManufacturerId)),
                                        new FilterParameter(nameof(Model.SearchStoreId)),
                                        new FilterParameter(nameof(Model.SearchVendorId))
                                    },
                                    ColumnCollection = new List<ColumnProperty>
                                    {
                                        new ColumnProperty(nameof(ProductModel.Id))
                                        {
                                            IsMasterCheckBox = true,
                                            Render = new RenderCheckBox(nameof(AddProductToClassificationModel.SelectedProductIds)),
                                            ClassName =  NopColumnClassDefaults.CenterAll,
                                            Width = "50"
                                        },
                                        new ColumnProperty(nameof(ProductModel.Name))
                                        {
                                            Title = T("Admin.Catalog.Products.Fields.Name").Text
                                        },
                                        new ColumnProperty(nameof(ProductModel.Sku))
                                        {
                                            Title = T("Admin.Catalog.Products.Fields.Sku").Text
                                        },
                                        new ColumnProperty(nameof(ProductModel.Price))
                                        {
                                            Title = T("Admin.Catalog.Products.Fields.Price").Text,
                                            Render = new RenderCustom("renderColumnPrice")
                                        },
                                        new ColumnProperty(nameof(ProductModel.Published))
                                        {
                                            Title = T("Admin.Catalog.Products.Fields.Published").Text,
                                            Width = "100",
                                            ClassName = NopColumnClassDefaults.CenterAll,
                                            Render = new RenderBoolean()
                                        }
                                    }
                                })
                            </div>
                            <div class="card-footer">
                                <button type="submit" name="save" class="btn btn-primary">
                                    <i class="far fa-floppy-disk"></i>
                                    @T("Admin.Common.Select")
                                </button>
                            </div>

                            <script>
                                function renderColumnPrice(data, type, row, meta) {
                                    return (row.ProductTypeId != @((int)ProductType.GroupedProduct)) ? data : null;
                                }
                            </script>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </form>
}